#A 6.2

Vandermonde matrices in Julia. Write a function that takes a positive integer n and an m-vector t as inputs and generates the corresponding m x n Vandermonde matrix.


Solution:


A function that takes integer n and m-vector t

In [1]:
function generateVandermondeMatrix( n, t, V)
    for j = 1 : n
        V[:,j] = t.^(j - 1)
    end
end

generateVandermondeMatrix (generic function with 1 method)

Initializing Empty matrix of size m x n

In [2]:
println("Enter m and n for Vandermonde Matrix\nm : ")
m = parse(Int64, readline())

Enter m and n for Vandermonde Matrix
m : 


4

In [3]:
println("n : ")
n = parse(Int64, readline())

n : 


5

Initializing n-vector t

In [4]:
t = Vector{Int64}()
println("Input the values of m-vector t : ")
for i = 1 : m
    push!(t, parse(Int64, readline()))
end

t

Input the values of m-vector t : 


4-element Vector{Int64}:
 1
 2
 3
 4

Initialize empty Vandermonde Matrix m x n

In [5]:
V = zeros(Int64, m, n)

4×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

Generating Vandermonde Matrix

In [6]:
generateVandermondeMatrix(n, t, V)
V

4×5 Matrix{Int64}:
 1  1   1   1    1
 1  2   4   8   16
 1  3   9  27   81
 1  4  16  64  256