# A 7.3

Reading the audiofile

In [2]:
using WAV
x, f = wavread("audio_filtering_original.wav")
x = vec(x)

441000-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.2860805094242096
 0.29850155115127563
 0.299630731344223
 0.28992584347724915
 0.2713095545768738
 0.24967192113399506
 0.23129978775978088
 0.21637623012065887
 0.20450453460216522
 0.19547104835510254
 0.18588824570178986
 0.17609180510044098

In [3]:
wavplay(x, f)

# a)

Convolving the input audio with $h^{smooth}$ vector

In [4]:
using DSP
h_smooth = 1 / 44 * ones(44)
output = conv(h_smooth, x)

441043-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.06601708551699467
 0.05951525575735354
 0.05273112959482454
 0.045921340246092186
 0.039332116530700165
 0.033165990290316666
 0.027491628446362243
 0.022234815088185415
 0.01731717349453407
 0.012669343162666671
 0.008226819336414365
 0.004002086479555481

Playing the output 

In [5]:
wavplay(output, f)

In the output audio above, the final amplitude is $\frac{1}{44}th$ of an amplitude combined with the previous 43 values i.e the average amplitude values of every 1ms

This results in the audio being pleasant to hear, whereas in the original audio the rough edges were clearly felt while hearing. This overall will result in a smooth audio curve.

# b)

Computing k

k should be of length 441000*0.25/10

In [6]:
k = Int64(size(x,1) * 0.25 / 10)

11025

Creating the $h^{echo}$ vector

k+1-Vector $h^{echo}$ = [1,0,0,...,0.5]

In [7]:
h_echo = 0 * ones(k)
h_echo[1] = 1
push!(h_echo, 0.5)

11026-element Vector{Float64}:
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.5

Computing the audio vector with echo

In [8]:
output_echo = conv(h_echo, x)

452025-element Vector{Float64}:
 -3.122502256758253e-17
  0.0
 -1.214306433183765e-17
 -1.3010426069826053e-17
 -2.42861286636753e-17
 -9.324138683375338e-18
  1.214306433183765e-17
  3.5128150388530344e-17
  6.938893903907228e-18
 -6.938893903907228e-18
 -1.734723475976807e-18
 -7.37257477290143e-18
 -1.3877787807814457e-17
  ⋮
  0.14304025471210485
  0.14925077557563776
  0.14981536567211157
  0.14496292173862457
  0.13565477728843683
  0.12483596056699751
  0.11564989387989044
  0.10818811506032945
  0.10225226730108262
  0.09773552417755121
  0.09294412285089498
  0.08804590255022045

Playing the echo output

In [9]:
wavplay(output_echo, f)

Computing the audio vector with echo twice

In [11]:
output_echo_echo = conv(h_echo, conv(h_echo, x))

463050-element Vector{Float64}:
 -1.5612511283791264e-17
  1.8214596497756474e-17
 -3.2959746043559335e-17
 -3.209238430557093e-17
 -4.0766001685454967e-17
 -3.382710778154774e-17
  3.469446951953614e-17
  6.331740687315346e-17
 -2.42861286636753e-17
 -1.3877787807814457e-17
 -2.949029909160572e-17
  8.673617379884035e-18
  1.0408340855860843e-17
  ⋮
  0.07152012735605243
  0.07462538778781898
  0.07490768283605576
  0.07248146086931244
  0.06782738864421842
  0.062417980283498875
  0.057824946939945165
  0.054094057530164774
  0.05112613365054133
  0.04886776208877572
  0.046472061425447506
  0.04402295127511027

Playing the output with echo vector added twice

In [12]:
wavplay(output_echo_echo, f)

In the output sample $h^{echo}$ $*$ x there was an echo added after 0.25 second at half the amplitude and the echo was confirmed while playing the audio

In the output sample $h^{echo}$ $*$ $h^{echo}$ $*$ x there were two echo vectors convolved and hence the resultant audio had 3 additional echoes each at a different amplitude and this was confirmed while playing the audio