In [1]:
using LinearAlgebra

include("iris_flower_data.jl")
include("iris_multiclass_helpers.jl")

confusion_matrix (generic function with 1 method)

In [2]:
X_train = X[:,1:100]'
X_test = X[:,101:150]'
y_train = y[1:100]'
y_test = y[101:150]'

1×50 adjoint(::Vector{Float64}) with eltype Float64:
 2.0  3.0  2.0  2.0  1.0  1.0  3.0  3.0  …  1.0  3.0  1.0  2.0  1.0  2.0  1.0

In [3]:
y1_train = 1*(y_train .== 1)'
y1_test = 1*(y_test .== 1)'
y2_train = 1*(y_train .== 2)'
y2_test = 1*(y_test .== 2)'
y3_train = 1*(y_train .== 3)'
y3_test = 1*(y_test .== 3)';

In [4]:
A_train = [ones(100) X_train];

In [5]:
theta1 = A_train \ (2*y1_train .- 1)

5×1 Matrix{Float64}:
 -0.9947466749775586
  0.09153586094062746
  0.5698447506712916
 -0.3371231542607084
 -0.2950531091716144

In [6]:
theta2 = A_train \ (2*y2_train .- 1)

5×1 Matrix{Float64}:
  2.63355046469394
  0.08917974435999566
 -1.1278629884847786
  0.1602264688097815
 -0.5514903082277343

In [7]:
theta3 = A_train \ (2*y3_train .- 1)

5×1 Matrix{Float64}:
 -2.638803789716383
 -0.18071560530062303
  0.5580182378134874
  0.17689668545092702
  0.8465434173993485

In [8]:
y1_hat_train = A_train*theta1 .> 0
y2_hat_train = A_train*theta2 .> 0
y3_hat_train = A_train*theta3 .> 0;

In [9]:
A_test = [ones(50) X_test]
y1_hat_test = A_test*theta1 .> 0
y2_hat_test = A_test*theta2 .> 0
y3_hat_test = A_test*theta3 .> 0;

In [10]:
using Statistics
error_rate(y, yhat) = mean(y .!= yhat)

error_rate (generic function with 1 method)

In [11]:
error1_train = error_rate(y1_train, y1_hat_train)
error2_train = error_rate(y2_train, y2_hat_train)
error3_train = error_rate(y3_train, y3_hat_train)
@show error1_train
@show error2_train
@show error3_train

error1_train = 0.0
error2_train = 0.28
error3_train = 0.1


0.1

In [12]:
error1_test = error_rate(y1_test, y1_hat_test)
error2_test = error_rate(y2_test, y2_hat_test)
error3_test = error_rate(y3_test, y3_hat_test)
@show error1_test
@show error2_test
@show error3_test

error1_test = 0.0
error2_test = 0.24
error3_test = 0.02


0.02