In [5]:
using LinearAlgebra
using MLJ

include("price_elasticity.jl")

In [6]:
(m1, n1) = size(Prices)
price_delta = zeros(m1, n1)
for i in 1:m1
    for j in 1:n1
        price_delta[i, j] = (Prices[i, j] - p_nom[i])/ p_nom[i]
    end
end
price_delta

5×75 Matrix{Float64}:
 -0.051424    -0.0149436   0.0775703  …  0.0600145   0.0563037    0.0215862
 -0.0302302    0.0561652  -0.0433173     0.0374761   0.101276     0.0625757
 -0.0367657   -0.0428182   0.0515471     0.0523813   0.0664217   -0.0339845
 -0.0937301   -0.0564496   0.0294006     0.0243497  -0.0180422    0.0195462
 -0.00227484  -0.0485082  -0.0809683     0.0638806  -0.00242106  -0.051104

In [7]:
(m2, n2) = size(Demands)
demand_delta = zeros(m2, n2)
for i in 1:m2
    for j in 1:n2
        demand_delta[i, j] = (Demands[i, j] - d_nom[i])/ d_nom[i]
    end
end
demand_delta

5×75 Matrix{Float64}:
  0.160915   0.041291    0.153608   …   0.00740388  -0.22383     0.322254
  0.655052  -0.145873    0.0712007      0.130662     0.0647327   0.0368358
 -0.322118  -0.248818   -0.180494      -0.11351     -0.144461   -0.162057
  0.260561   0.0780381  -0.250927      -0.170021     0.0930676   0.438625
  0.108005  -0.0951855   0.117042      -0.14356     -0.16178     0.159025

In [8]:
E = zeros(m1,m2);
for i in 1:m1
    E[i,:] = demand_delta[i,:] \ price_delta'
end
E

5×5 Matrix{Float64}:
 -0.0804511    0.0103458   -0.0839659   -0.0261969  -0.0148971
  0.00838631  -0.0347895   -0.00642602  -0.0475389  -0.0474
 -0.0458354    0.0148483   -0.0303634   -0.0174009  -0.0422333
 -0.0058114    0.00113364  -0.00169382  -0.0734906   0.036418
  0.0284484   -0.0687943   -0.0731857    0.0254066  -0.076902

In [9]:
delta_phat = E*(E\price_delta)

5×75 Matrix{Float64}:
 -0.051424    -0.0149436   0.0775703  …  0.0600145   0.0563037    0.0215862
 -0.0302302    0.0561652  -0.0433173     0.0374761   0.101276     0.0625757
 -0.0367657   -0.0428182   0.0515471     0.0523813   0.0664217   -0.0339845
 -0.0937301   -0.0564496   0.0294006     0.0243497  -0.0180422    0.0195462
 -0.00227484  -0.0485082  -0.0809683     0.0638806  -0.00242106  -0.051104

In [10]:
rms(delta_phat,price_delta)

3.4828535264082376e-17